version: '2'
services:
  service1:
    container_name: service1
    build: .
    image: test/service1:latest
    command: ["./loop.sh"]
    volumes:
      - .:/app
    ports:
      - "3001:3001"
  service2:
    container_name: service2
    build: .
    image: test/service1:latest
    command: ["./loop.sh"]
    volumes:
      - .:/app_2
    ports:
      - "3002:3002"
